param (
    [string]$ProjectPath,
    [string]$Csproj,
    [string]$DotnetPath = "dotnet",
    [string]$ProcessId
)

$migrationName = "AutoGeneratedMigration_$(Get-Date -Format 'yyyyMMddHHmmss')"

Stop-Process -Id $ProcessId -Force

Write-Host "Generating EF migration: $migrationName"
Push-Location $ProjectPath

& $DotnetPath ef migrations add $migrationName --project $Csproj
& $DotnetPath ef database update --project $Csproj --no-build

Write-Host "Restarting application..."
& $DotnetPath run --project $Csproj --no-build
Write-Host "Done. Migration applied and app restarted."