#!/bin/sh
set -e

cd "$(dirname -- "$0")/../../"
PROJECT_ROOT=$(pwd)

echo "Running pre-commit checks..."

echo "Formatting frontend files in CCUI.DAPPI..."
cd "$PROJECT_ROOT/CCUI.DAPPI"

echo "Formatting with Prettier..."
npx prettier --write "**/*.{js,ts,html,css,scss,json}"

echo "Linting and fixing JS/TS with ESLint..."
npx eslint --fix "**/*.{js,ts}"

echo "🔧 Formatting .NET files..."
cd "$PROJECT_ROOT"

if ! dotnet tool list --global | grep -q "dotnet-format"; then
  echo "dotnet-format is not installed. Installing it globally..."
  dotnet tool install -g dotnet-format
fi

echo "Formatting Dappi.HeadlessCms..."
dotnet format ./Dappi.HeadlessCms

echo "Formatting Dappi.SourceGenerator..."
dotnet format ./Dappi.SourceGenerator

cd "$PROJECT_ROOT"
git add .

echo "✅ Pre-commit checks completed successfully!"