// <auto-generated />
using Dappi.Core.Models;

namespace GeneratedPermissions
{
    public static partial class PermissionsMeta
    {
        public static readonly System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IReadOnlyList<MethodRouteEntry>> Controllers =
            new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IReadOnlyList<MethodRouteEntry>>
            {
                { "{{ controller_name }}", new System.Collections.Generic.List<MethodRouteEntry>
                    {
                        {{ for method in methods }}
                        new MethodRouteEntry { MethodName = "{{ method.method_name }}", HttpRoute = "{{ method.http_route }}" },
                        {{ end }}
                    }
                }
            };
    }
}
