// <auto-generated />
using System.Collections.Generic;
using Dappi.Core.Models;

namespace GeneratedPermissions
{
    public static partial class PermissionsMeta
    {
        public static readonly IReadOnlyDictionary<string, IReadOnlyList<MethodRouteEntry>> Controllers =
            new Dictionary<string, IReadOnlyList<MethodRouteEntry>>
            {
                {{ for controller in controllers }}
                {
                    "{{ controller.controller_name }}",
                    new List<MethodRouteEntry>
                    {
                        {{ for method in controller.methods }}
                        new MethodRouteEntry
                        {
                            MethodName = "{{ method.method_name }}",
                            HttpRoute = "{{ method.http_route }}"
                        }{{ if !for.last }},{{ end }}
                        {{ end }}
                    }
                }{{ if !for.last }},{{ end }}
                {{ end }}
            };
    }
}
